name = "AbstractNumbers"
uuid = "85c772de-338a-5e7f-b815-41e76c26ac1f"
version = "0.2.1"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "0.10, 0.9, 0.8"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
